// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

namespace ccxt;

public partial class zebpayfutures : Exchange
{
    public zebpayfutures (object args = null): base(args) {}

    public async Task<object> publicGetCcxtSystemTime (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtSystemTime",parameters);
    }

    public async Task<object> publicGetCcxtSystemStatus (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtSystemStatus",parameters);
    }

    public async Task<object> publicGetCcxtExchangeTradefee (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtExchangeTradefee",parameters);
    }

    public async Task<object> publicGetCcxtExchangeTradefees (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtExchangeTradefees",parameters);
    }

    public async Task<object> publicGetCcxtMarketOrderBook (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtMarketOrderBook",parameters);
    }

    public async Task<object> publicGetCcxtMarketTicker24Hr (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtMarketTicker24Hr",parameters);
    }

    public async Task<object> publicGetCcxtMarketMarkets (object parameters = null)
    {
        return await this.callAsync ("publicGetCcxtMarketMarkets",parameters);
    }

    public async Task<object> privateGetCcxtWalletBalance (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtWalletBalance",parameters);
    }

    public async Task<object> privateGetCcxtTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtTradeOrder",parameters);
    }

    public async Task<object> privateGetCcxtTradeOrderOpenOrders (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtTradeOrderOpenOrders",parameters);
    }

    public async Task<object> privateGetCcxtTradeUserLeverages (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtTradeUserLeverages",parameters);
    }

    public async Task<object> privateGetCcxtTradeUserLeverage (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtTradeUserLeverage",parameters);
    }

    public async Task<object> privateGetCcxtTradePositions (object parameters = null)
    {
        return await this.callAsync ("privateGetCcxtTradePositions",parameters);
    }

    public async Task<object> privatePostCcxtTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradeOrder",parameters);
    }

    public async Task<object> privatePostCcxtTradeOrderAddTPSL (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradeOrderAddTPSL",parameters);
    }

    public async Task<object> privatePostCcxtTradeAddMargin (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradeAddMargin",parameters);
    }

    public async Task<object> privatePostCcxtTradeReduceMargin (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradeReduceMargin",parameters);
    }

    public async Task<object> privatePostCcxtTradePositionClose (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradePositionClose",parameters);
    }

    public async Task<object> privatePostCcxtTradeUpdateUserLeverage (object parameters = null)
    {
        return await this.callAsync ("privatePostCcxtTradeUpdateUserLeverage",parameters);
    }

    public async Task<object> privateDeleteCcxtTradeOrder (object parameters = null)
    {
        return await this.callAsync ("privateDeleteCcxtTradeOrder",parameters);
    }

}