// -------------------------------------------------------------------------------

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

// -------------------------------------------------------------------------------

package ccxt

func (this *zebpayfutures) PublicGetCcxtSystemTime (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtSystemTime", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtSystemStatus (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtSystemStatus", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtExchangeTradefee (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtExchangeTradefee", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtExchangeTradefees (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtExchangeTradefees", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtMarketOrderBook (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtMarketOrderBook", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtMarketTicker24Hr (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtMarketTicker24Hr", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PublicGetCcxtMarketMarkets (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("publicGetCcxtMarketMarkets", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtWalletBalance (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtWalletBalance", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtTradeOrder (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtTradeOrder", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtTradeOrderOpenOrders (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtTradeOrderOpenOrders", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtTradeUserLeverages (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtTradeUserLeverages", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtTradeUserLeverage (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtTradeUserLeverage", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateGetCcxtTradePositions (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateGetCcxtTradePositions", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradeOrder (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradeOrder", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradeOrderAddTPSL (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradeOrderAddTPSL", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradeAddMargin (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradeAddMargin", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradeReduceMargin (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradeReduceMargin", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradePositionClose (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradePositionClose", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivatePostCcxtTradeUpdateUserLeverage (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privatePostCcxtTradeUpdateUserLeverage", parameters))
       PanicOnError(ch)
   }()
   return ch
}

func (this *zebpayfutures) PrivateDeleteCcxtTradeOrder (args ...interface{}) <-chan interface{} {
   parameters := GetArg(args, 0, nil)
   ch := make(chan interface{})
   go func() {
       defer close(ch)
       defer func() {
           if r := recover(); r != nil {
               ch <- "panic:" + ToString(r)
           }
       }()
       ch <- (<-this.callEndpoint ("privateDeleteCcxtTradeOrder", parameters))
       PanicOnError(ch)
   }()
   return ch
}
